Search.appendIndex(
    [
                {
            "fqsen": "\\simpleRdf\\BlankNode",
            "name": "BlankNode",
            "summary": "Description\u0020of\u0020BlankNode",
            "url": "classes/simpleRdf-BlankNode.html"
        },                {
            "fqsen": "\\simpleRdf\\BlankNode\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/simpleRdf-BlankNode.html#method___construct"
        },                {
            "fqsen": "\\simpleRdf\\BlankNode\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/simpleRdf-BlankNode.html#method___toString"
        },                {
            "fqsen": "\\simpleRdf\\BlankNode\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/simpleRdf-BlankNode.html#method_equals"
        },                {
            "fqsen": "\\simpleRdf\\BlankNode\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "",
            "url": "classes/simpleRdf-BlankNode.html#method_getValue"
        },                {
            "fqsen": "\\simpleRdf\\BlankNode\u003A\u003A\u0024n",
            "name": "n",
            "summary": "",
            "url": "classes/simpleRdf-BlankNode.html#property_n"
        },                {
            "fqsen": "\\simpleRdf\\BlankNode\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/simpleRdf-BlankNode.html#property_id"
        },                {
            "fqsen": "\\simpleRdf\\DataFactory",
            "name": "DataFactory",
            "summary": "Description\u0020of\u0020DataFactory",
            "url": "classes/simpleRdf-DataFactory.html"
        },                {
            "fqsen": "\\simpleRdf\\DataFactory\u003A\u003AblankNode\u0028\u0029",
            "name": "blankNode",
            "summary": "",
            "url": "classes/simpleRdf-DataFactory.html#method_blankNode"
        },                {
            "fqsen": "\\simpleRdf\\DataFactory\u003A\u003AnamedNode\u0028\u0029",
            "name": "namedNode",
            "summary": "",
            "url": "classes/simpleRdf-DataFactory.html#method_namedNode"
        },                {
            "fqsen": "\\simpleRdf\\DataFactory\u003A\u003AdefaultGraph\u0028\u0029",
            "name": "defaultGraph",
            "summary": "",
            "url": "classes/simpleRdf-DataFactory.html#method_defaultGraph"
        },                {
            "fqsen": "\\simpleRdf\\DataFactory\u003A\u003Aliteral\u0028\u0029",
            "name": "literal",
            "summary": "",
            "url": "classes/simpleRdf-DataFactory.html#method_literal"
        },                {
            "fqsen": "\\simpleRdf\\DataFactory\u003A\u003Aquad\u0028\u0029",
            "name": "quad",
            "summary": "",
            "url": "classes/simpleRdf-DataFactory.html#method_quad"
        },                {
            "fqsen": "\\simpleRdf\\DataFactory\u003A\u003AquadTemplate\u0028\u0029",
            "name": "quadTemplate",
            "summary": "",
            "url": "classes/simpleRdf-DataFactory.html#method_quadTemplate"
        },                {
            "fqsen": "\\simpleRdf\\DataFactory\u003A\u003Avariable\u0028\u0029",
            "name": "variable",
            "summary": "",
            "url": "classes/simpleRdf-DataFactory.html#method_variable"
        },                {
            "fqsen": "\\simpleRdf\\Dataset",
            "name": "Dataset",
            "summary": "Description\u0020of\u0020Graph",
            "url": "classes/simpleRdf-Dataset.html"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method___construct"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method___toString"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_equals"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Adds\u0020set\u0020of\u0020quads.",
            "url": "classes/simpleRdf-Dataset.html#method_add"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003Acopy\u0028\u0029",
            "name": "copy",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_copy"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003AcopyExcept\u0028\u0029",
            "name": "copyExcept",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_copyExcept"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003Aunion\u0028\u0029",
            "name": "union",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_union"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003Axor\u0028\u0029",
            "name": "xor",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_xor"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_delete"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003AdeleteExcept\u0028\u0029",
            "name": "deleteExcept",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_deleteExcept"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003AforEach\u0028\u0029",
            "name": "forEach",
            "summary": "Iterates\u0020trough\u0020all\u0020quads\u0020replacing\u0020them\u0020with\u0020a\u0020callback\u0020result.",
            "url": "classes/simpleRdf-Dataset.html#method_forEach"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_current"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003Akey\u0028\u0029",
            "name": "key",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_key"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003Anext\u0028\u0029",
            "name": "next",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_next"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003Arewind\u0028\u0029",
            "name": "rewind",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_rewind"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003Avalid\u0028\u0029",
            "name": "valid",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_valid"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_count"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_offsetExists"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003Aexists\u0028\u0029",
            "name": "exists",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_exists"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_offsetGet"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_get"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_offsetSet"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_set"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_offsetUnset"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003AfindMatchingQuads\u0028\u0029",
            "name": "findMatchingQuads",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_findMatchingQuads"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003AfindNotMatchingQuads\u0028\u0029",
            "name": "findNotMatchingQuads",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_findNotMatchingQuads"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003AprepareMatchFunction\u0028\u0029",
            "name": "prepareMatchFunction",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_prepareMatchFunction"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003AcheckIteratorEnd\u0028\u0029",
            "name": "checkIteratorEnd",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_checkIteratorEnd"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003Amap\u0028\u0029",
            "name": "map",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_map"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003Areduce\u0028\u0029",
            "name": "reduce",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_reduce"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003Aany\u0028\u0029",
            "name": "any",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_any"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003Aevery\u0028\u0029",
            "name": "every",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_every"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003Anone\u0028\u0029",
            "name": "none",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#method_none"
        },                {
            "fqsen": "\\simpleRdf\\Dataset\u003A\u003A\u0024quads",
            "name": "quads",
            "summary": "",
            "url": "classes/simpleRdf-Dataset.html#property_quads"
        },                {
            "fqsen": "\\simpleRdf\\Literal",
            "name": "Literal",
            "summary": "Description\u0020of\u0020Literal",
            "url": "classes/simpleRdf-Literal.html"
        },                {
            "fqsen": "\\simpleRdf\\Literal\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Creates\u0020a\u0020new\u0020literal.",
            "url": "classes/simpleRdf-Literal.html#method___construct"
        },                {
            "fqsen": "\\simpleRdf\\Literal\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/simpleRdf-Literal.html#method___toString"
        },                {
            "fqsen": "\\simpleRdf\\Literal\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "Returns\u0020literal\u0027s\u0020value.",
            "url": "classes/simpleRdf-Literal.html#method_getValue"
        },                {
            "fqsen": "\\simpleRdf\\Literal\u003A\u003AgetLang\u0028\u0029",
            "name": "getLang",
            "summary": "Returns\u0020literal\u0027s\u0020language\u0020tag.",
            "url": "classes/simpleRdf-Literal.html#method_getLang"
        },                {
            "fqsen": "\\simpleRdf\\Literal\u003A\u003AgetDatatype\u0028\u0029",
            "name": "getDatatype",
            "summary": "Returns\u0020literal\u0027s\u0020datatype.",
            "url": "classes/simpleRdf-Literal.html#method_getDatatype"
        },                {
            "fqsen": "\\simpleRdf\\Literal\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/simpleRdf-Literal.html#method_equals"
        },                {
            "fqsen": "\\simpleRdf\\Literal\u003A\u003AwithValue\u0028\u0029",
            "name": "withValue",
            "summary": "Returns\u0020a\u0020new\u0020literal\u0020being\u0020a\u0020copy\u0020of\u0020this\u0020one\u0020with\u0020a\u0020given\u0020value.",
            "url": "classes/simpleRdf-Literal.html#method_withValue"
        },                {
            "fqsen": "\\simpleRdf\\Literal\u003A\u003AwithLang\u0028\u0029",
            "name": "withLang",
            "summary": "Returns\u0020a\u0020new\u0020literal\u0020being\u0020a\u0020copy\u0020of\u0020this\u0020one\u0020with\u0020a\u0020lang\u0020tag\u0020set\u0020to\na\u0020given\u0020value.",
            "url": "classes/simpleRdf-Literal.html#method_withLang"
        },                {
            "fqsen": "\\simpleRdf\\Literal\u003A\u003AwithDatatype\u0028\u0029",
            "name": "withDatatype",
            "summary": "Returns\u0020a\u0020new\u0020literal\u0020being\u0020a\u0020copy\u0020with\u0020this\u0020one\u0020with\u0020datatype\u0020set\u0020to\na\u0020given\u0020value.",
            "url": "classes/simpleRdf-Literal.html#method_withDatatype"
        },                {
            "fqsen": "\\simpleRdf\\Literal\u003A\u003A\u0024value",
            "name": "value",
            "summary": "",
            "url": "classes/simpleRdf-Literal.html#property_value"
        },                {
            "fqsen": "\\simpleRdf\\Literal\u003A\u003A\u0024lang",
            "name": "lang",
            "summary": "",
            "url": "classes/simpleRdf-Literal.html#property_lang"
        },                {
            "fqsen": "\\simpleRdf\\Literal\u003A\u003A\u0024datatype",
            "name": "datatype",
            "summary": "",
            "url": "classes/simpleRdf-Literal.html#property_datatype"
        },                {
            "fqsen": "\\simpleRdf\\NamedNode",
            "name": "NamedNode",
            "summary": "Description\u0020of\u0020Iri",
            "url": "classes/simpleRdf-NamedNode.html"
        },                {
            "fqsen": "\\simpleRdf\\NamedNode\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/simpleRdf-NamedNode.html#method___construct"
        },                {
            "fqsen": "\\simpleRdf\\NamedNode\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/simpleRdf-NamedNode.html#method___toString"
        },                {
            "fqsen": "\\simpleRdf\\NamedNode\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "",
            "url": "classes/simpleRdf-NamedNode.html#method_getValue"
        },                {
            "fqsen": "\\simpleRdf\\NamedNode\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/simpleRdf-NamedNode.html#method_equals"
        },                {
            "fqsen": "\\simpleRdf\\NamedNode\u003A\u003A\u0024iri",
            "name": "iri",
            "summary": "",
            "url": "classes/simpleRdf-NamedNode.html#property_iri"
        },                {
            "fqsen": "\\simpleRdf\\Quad",
            "name": "Quad",
            "summary": "Description\u0020of\u0020Triple",
            "url": "classes/simpleRdf-Quad.html"
        },                {
            "fqsen": "\\simpleRdf\\Quad\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/simpleRdf-Quad.html#method___construct"
        },                {
            "fqsen": "\\simpleRdf\\Quad\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/simpleRdf-Quad.html#method___toString"
        },                {
            "fqsen": "\\simpleRdf\\Quad\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/simpleRdf-Quad.html#method_equals"
        },                {
            "fqsen": "\\simpleRdf\\Quad\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "",
            "url": "classes/simpleRdf-Quad.html#method_getValue"
        },                {
            "fqsen": "\\simpleRdf\\Quad\u003A\u003AgetSubject\u0028\u0029",
            "name": "getSubject",
            "summary": "",
            "url": "classes/simpleRdf-Quad.html#method_getSubject"
        },                {
            "fqsen": "\\simpleRdf\\Quad\u003A\u003AgetPredicate\u0028\u0029",
            "name": "getPredicate",
            "summary": "",
            "url": "classes/simpleRdf-Quad.html#method_getPredicate"
        },                {
            "fqsen": "\\simpleRdf\\Quad\u003A\u003AgetObject\u0028\u0029",
            "name": "getObject",
            "summary": "",
            "url": "classes/simpleRdf-Quad.html#method_getObject"
        },                {
            "fqsen": "\\simpleRdf\\Quad\u003A\u003AgetGraphIri\u0028\u0029",
            "name": "getGraphIri",
            "summary": "Null\u0020is\u0020not\u0020allowed\u0020to\u0020deal\u0020with\u0020the\u0020ambiguity\u0020between\u0020DefaultGraph\u0020and\nnull\u0020which\u0020mean\u0020the\u0020same\u0020\u0028although\u0020it\u0020should\u0020be\u0020noted\u0020that\u0020all\u0020quads\u0020in\nNamedNode\/BlankNode\u0020graphs\u0020also\u0020belong\u0020to\u0020the\u0020DefaultGraph\u0029.",
            "url": "classes/simpleRdf-Quad.html#method_getGraphIri"
        },                {
            "fqsen": "\\simpleRdf\\Quad\u003A\u003AwithSubject\u0028\u0029",
            "name": "withSubject",
            "summary": "",
            "url": "classes/simpleRdf-Quad.html#method_withSubject"
        },                {
            "fqsen": "\\simpleRdf\\Quad\u003A\u003AwithPredicate\u0028\u0029",
            "name": "withPredicate",
            "summary": "",
            "url": "classes/simpleRdf-Quad.html#method_withPredicate"
        },                {
            "fqsen": "\\simpleRdf\\Quad\u003A\u003AwithObject\u0028\u0029",
            "name": "withObject",
            "summary": "",
            "url": "classes/simpleRdf-Quad.html#method_withObject"
        },                {
            "fqsen": "\\simpleRdf\\Quad\u003A\u003AwithGraphIri\u0028\u0029",
            "name": "withGraphIri",
            "summary": "",
            "url": "classes/simpleRdf-Quad.html#method_withGraphIri"
        },                {
            "fqsen": "\\simpleRdf\\Quad\u003A\u003A\u0024subject",
            "name": "subject",
            "summary": "",
            "url": "classes/simpleRdf-Quad.html#property_subject"
        },                {
            "fqsen": "\\simpleRdf\\Quad\u003A\u003A\u0024predicate",
            "name": "predicate",
            "summary": "",
            "url": "classes/simpleRdf-Quad.html#property_predicate"
        },                {
            "fqsen": "\\simpleRdf\\Quad\u003A\u003A\u0024object",
            "name": "object",
            "summary": "",
            "url": "classes/simpleRdf-Quad.html#property_object"
        },                {
            "fqsen": "\\simpleRdf\\Quad\u003A\u003A\u0024graphIri",
            "name": "graphIri",
            "summary": "",
            "url": "classes/simpleRdf-Quad.html#property_graphIri"
        },                {
            "fqsen": "\\simpleRdf\\QuadTemplate",
            "name": "QuadTemplate",
            "summary": "Description\u0020of\u0020QuadTemplate",
            "url": "classes/simpleRdf-QuadTemplate.html"
        },                {
            "fqsen": "\\simpleRdf\\QuadTemplate\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "At\u0020least\u0020one\u0020parameter\u0020has\u0020to\u0020be\u0020not\u0020null.",
            "url": "classes/simpleRdf-QuadTemplate.html#method___construct"
        },                {
            "fqsen": "\\simpleRdf\\QuadTemplate\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/simpleRdf-QuadTemplate.html#method___toString"
        },                {
            "fqsen": "\\simpleRdf\\QuadTemplate\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/simpleRdf-QuadTemplate.html#method_equals"
        },                {
            "fqsen": "\\simpleRdf\\QuadTemplate\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "",
            "url": "classes/simpleRdf-QuadTemplate.html#method_getValue"
        },                {
            "fqsen": "\\simpleRdf\\QuadTemplate\u003A\u003AgetSubject\u0028\u0029",
            "name": "getSubject",
            "summary": "",
            "url": "classes/simpleRdf-QuadTemplate.html#method_getSubject"
        },                {
            "fqsen": "\\simpleRdf\\QuadTemplate\u003A\u003AgetPredicate\u0028\u0029",
            "name": "getPredicate",
            "summary": "",
            "url": "classes/simpleRdf-QuadTemplate.html#method_getPredicate"
        },                {
            "fqsen": "\\simpleRdf\\QuadTemplate\u003A\u003AgetObject\u0028\u0029",
            "name": "getObject",
            "summary": "",
            "url": "classes/simpleRdf-QuadTemplate.html#method_getObject"
        },                {
            "fqsen": "\\simpleRdf\\QuadTemplate\u003A\u003AgetGraphIri\u0028\u0029",
            "name": "getGraphIri",
            "summary": "DefaultGraph\u0020is\u0020skipped\u0020to\u0020avoid\u0020ambiguity\u0020between\u0020null\u0020and\u0020DefaultGraph\n\u0028as\u0020all\u0020quads\u0020belong\u0020to\u0020the\u0020DefaultGraph\u0020it\u0020effectively\u0020means\u0020no\u0020filter\u0020at\nall,\u0020just\u0020like\u0020null\u0029.",
            "url": "classes/simpleRdf-QuadTemplate.html#method_getGraphIri"
        },                {
            "fqsen": "\\simpleRdf\\QuadTemplate\u003A\u003AwithSubject\u0028\u0029",
            "name": "withSubject",
            "summary": "",
            "url": "classes/simpleRdf-QuadTemplate.html#method_withSubject"
        },                {
            "fqsen": "\\simpleRdf\\QuadTemplate\u003A\u003AwithPredicate\u0028\u0029",
            "name": "withPredicate",
            "summary": "",
            "url": "classes/simpleRdf-QuadTemplate.html#method_withPredicate"
        },                {
            "fqsen": "\\simpleRdf\\QuadTemplate\u003A\u003AwithObject\u0028\u0029",
            "name": "withObject",
            "summary": "",
            "url": "classes/simpleRdf-QuadTemplate.html#method_withObject"
        },                {
            "fqsen": "\\simpleRdf\\QuadTemplate\u003A\u003AwithGraphIri\u0028\u0029",
            "name": "withGraphIri",
            "summary": "",
            "url": "classes/simpleRdf-QuadTemplate.html#method_withGraphIri"
        },                {
            "fqsen": "\\simpleRdf\\QuadTemplate\u003A\u003A\u0024subject",
            "name": "subject",
            "summary": "",
            "url": "classes/simpleRdf-QuadTemplate.html#property_subject"
        },                {
            "fqsen": "\\simpleRdf\\QuadTemplate\u003A\u003A\u0024predicate",
            "name": "predicate",
            "summary": "",
            "url": "classes/simpleRdf-QuadTemplate.html#property_predicate"
        },                {
            "fqsen": "\\simpleRdf\\QuadTemplate\u003A\u003A\u0024object",
            "name": "object",
            "summary": "",
            "url": "classes/simpleRdf-QuadTemplate.html#property_object"
        },                {
            "fqsen": "\\simpleRdf\\QuadTemplate\u003A\u003A\u0024graphIri",
            "name": "graphIri",
            "summary": "",
            "url": "classes/simpleRdf-QuadTemplate.html#property_graphIri"
        },                {
            "fqsen": "\\simpleRdf\\RdfException",
            "name": "RdfException",
            "summary": "",
            "url": "classes/simpleRdf-RdfException.html"
        },                {
            "fqsen": "\\simpleRdf\\RdfNamespace",
            "name": "RdfNamespace",
            "summary": "Description\u0020of\u0020RdfNamespace",
            "url": "classes/simpleRdf-RdfNamespace.html"
        },                {
            "fqsen": "\\simpleRdf\\RdfNamespace\u003A\u003AgetNamedNode\u0028\u0029",
            "name": "getNamedNode",
            "summary": "",
            "url": "classes/simpleRdf-RdfNamespace.html#method_getNamedNode"
        },                {
            "fqsen": "\\rdfHelpers\\DefaultGraph",
            "name": "DefaultGraph",
            "summary": "Description\u0020of\u0020DefaultGraph",
            "url": "classes/rdfHelpers-DefaultGraph.html"
        },                {
            "fqsen": "\\rdfHelpers\\DefaultGraph\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfHelpers-DefaultGraph.html#method___construct"
        },                {
            "fqsen": "\\rdfHelpers\\DefaultGraph\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/rdfHelpers-DefaultGraph.html#method___toString"
        },                {
            "fqsen": "\\rdfHelpers\\DefaultGraph\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "",
            "url": "classes/rdfHelpers-DefaultGraph.html#method_getValue"
        },                {
            "fqsen": "\\rdfHelpers\\DefaultGraph\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/rdfHelpers-DefaultGraph.html#method_equals"
        },                {
            "fqsen": "\\rdfHelpers\\GenericQuadIterator",
            "name": "GenericQuadIterator",
            "summary": "Wrapper\u0020making\u0020almost\u0020anything\u0020\u0028e.g.\u0020array,\u0020generator\u0020or\u0020a\u0020single\u0020Quad\u0020object\u0029\na\u0020QuadIterator.",
            "url": "classes/rdfHelpers-GenericQuadIterator.html"
        },                {
            "fqsen": "\\rdfHelpers\\GenericQuadIterator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfHelpers-GenericQuadIterator.html#method___construct"
        },                {
            "fqsen": "\\rdfHelpers\\GenericQuadIterator\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "",
            "url": "classes/rdfHelpers-GenericQuadIterator.html#method_current"
        },                {
            "fqsen": "\\rdfHelpers\\GenericQuadIterator\u003A\u003Akey\u0028\u0029",
            "name": "key",
            "summary": "",
            "url": "classes/rdfHelpers-GenericQuadIterator.html#method_key"
        },                {
            "fqsen": "\\rdfHelpers\\GenericQuadIterator\u003A\u003Anext\u0028\u0029",
            "name": "next",
            "summary": "",
            "url": "classes/rdfHelpers-GenericQuadIterator.html#method_next"
        },                {
            "fqsen": "\\rdfHelpers\\GenericQuadIterator\u003A\u003Arewind\u0028\u0029",
            "name": "rewind",
            "summary": "",
            "url": "classes/rdfHelpers-GenericQuadIterator.html#method_rewind"
        },                {
            "fqsen": "\\rdfHelpers\\GenericQuadIterator\u003A\u003Avalid\u0028\u0029",
            "name": "valid",
            "summary": "",
            "url": "classes/rdfHelpers-GenericQuadIterator.html#method_valid"
        },                {
            "fqsen": "\\rdfHelpers\\GenericQuadIterator\u003A\u003A\u0024iter",
            "name": "iter",
            "summary": "",
            "url": "classes/rdfHelpers-GenericQuadIterator.html#property_iter"
        },                {
            "fqsen": "\\rdfHelpers\\NtriplesUtil",
            "name": "NtriplesUtil",
            "summary": "Description\u0020of\u0020Util",
            "url": "classes/rdfHelpers-NtriplesUtil.html"
        },                {
            "fqsen": "\\rdfHelpers\\NtriplesUtil\u003A\u003AescapeLiteral\u0028\u0029",
            "name": "escapeLiteral",
            "summary": "",
            "url": "classes/rdfHelpers-NtriplesUtil.html#method_escapeLiteral"
        },                {
            "fqsen": "\\rdfHelpers\\NtriplesUtil\u003A\u003AescapeIri\u0028\u0029",
            "name": "escapeIri",
            "summary": "",
            "url": "classes/rdfHelpers-NtriplesUtil.html#method_escapeIri"
        },                {
            "fqsen": "\\rdfHelpers\\NtriplesUtil\u003A\u003AserializeIri\u0028\u0029",
            "name": "serializeIri",
            "summary": "",
            "url": "classes/rdfHelpers-NtriplesUtil.html#method_serializeIri"
        },                {
            "fqsen": "\\rdfHelpers\\NtriplesUtil\u003A\u003AserializeLiteral\u0028\u0029",
            "name": "serializeLiteral",
            "summary": "",
            "url": "classes/rdfHelpers-NtriplesUtil.html#method_serializeLiteral"
        },                {
            "fqsen": "\\rdfHelpers\\NtriplesUtil\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "",
            "url": "classes/rdfHelpers-NtriplesUtil.html#method_serialize"
        },                {
            "fqsen": "\\rdfHelpers\\NtriplesUtil\u003A\u003A\u0024iriEscapeMap",
            "name": "iriEscapeMap",
            "summary": "Characters\u0020forbidden\u0020in\u0020n\u002Dtriples\u0020literals\u0020according\u0020to\nhttps\u003A\/\/www.w3.org\/TR\/n\u002Dtriples\/\u0023grammar\u002Dproduction\u002DIRIREF",
            "url": "classes/rdfHelpers-NtriplesUtil.html#property_iriEscapeMap"
        },                {
            "fqsen": "\\rdfHelpers\\NtriplesUtil\u003A\u003A\u0024literalEscapeMap",
            "name": "literalEscapeMap",
            "summary": "Characters\u0020forbidden\u0020in\u0020n\u002Dtriples\u0020literals\u0020according\u0020to\nhttps\u003A\/\/www.w3.org\/TR\/n\u002Dtriples\/\u0023grammar\u002Dproduction\u002DSTRING_LITERAL_QUOTE",
            "url": "classes/rdfHelpers-NtriplesUtil.html#property_literalEscapeMap"
        },                {
            "fqsen": "\\rdfHelpers\\RdfHelpersException",
            "name": "RdfHelpersException",
            "summary": "Description\u0020of\u0020RdfHelpersException",
            "url": "classes/rdfHelpers-RdfHelpersException.html"
        },                {
            "fqsen": "\\rdfHelpers\\RdfNamespace",
            "name": "RdfNamespace",
            "summary": "Provides\u0020an\u0020implementation\u0020of\u0020rdfInterface\\RdfNamespace.",
            "url": "classes/rdfHelpers-RdfNamespace.html"
        },                {
            "fqsen": "\\rdfHelpers\\RdfNamespace\u003A\u003AgetNamedNode\u0028\u0029",
            "name": "getNamedNode",
            "summary": "",
            "url": "classes/rdfHelpers-RdfNamespace.html#method_getNamedNode"
        },                {
            "fqsen": "\\rdfHelpers\\RdfNamespace\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Registers\u0020a\u0020given\u0020URL\u0020prefix.",
            "url": "classes/rdfHelpers-RdfNamespace.html#method_add"
        },                {
            "fqsen": "\\rdfHelpers\\RdfNamespace\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Drops\u0020a\u0020given\u0020short\u0020name\u0020and\u0020IRI\u0020prefix\u0020associated\u0020with\u0020it.",
            "url": "classes/rdfHelpers-RdfNamespace.html#method_remove"
        },                {
            "fqsen": "\\rdfHelpers\\RdfNamespace\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Returns\u0020a\u0020IRI\u0020prefix\u0020for\u0020a\u0020given\u0020short\u0020name.",
            "url": "classes/rdfHelpers-RdfNamespace.html#method_get"
        },                {
            "fqsen": "\\rdfHelpers\\RdfNamespace\u003A\u003AgetAll\u0028\u0029",
            "name": "getAll",
            "summary": "Returns\u0020associative\u0020array\u0020of\u0020all\u0020registered\u0020namespaces\u0020with\u0020array\u0020keys\nbeing\u0020namespace\u0020short\u0020names\u0020and\u0020array\u0020values\u0020containing\u0020URL\u0020prefixes.",
            "url": "classes/rdfHelpers-RdfNamespace.html#method_getAll"
        },                {
            "fqsen": "\\rdfHelpers\\RdfNamespace\u003A\u003Aexpand\u0028\u0029",
            "name": "expand",
            "summary": "Expands\u0020a\u0020shortened\u0020IRI\u0020to\u0020a\u0020NamedNode.",
            "url": "classes/rdfHelpers-RdfNamespace.html#method_expand"
        },                {
            "fqsen": "\\rdfHelpers\\RdfNamespace\u003A\u003Ashorten\u0028\u0029",
            "name": "shorten",
            "summary": "Shortens\u0020provided\u0020NamedNode\u0020IRI.",
            "url": "classes/rdfHelpers-RdfNamespace.html#method_shorten"
        },                {
            "fqsen": "\\rdfHelpers\\RdfNamespace\u003A\u003A\u0024n",
            "name": "n",
            "summary": "",
            "url": "classes/rdfHelpers-RdfNamespace.html#property_n"
        },                {
            "fqsen": "\\rdfHelpers\\RdfNamespace\u003A\u003A\u0024namespaces",
            "name": "namespaces",
            "summary": "",
            "url": "classes/rdfHelpers-RdfNamespace.html#property_namespaces"
        },                {
            "fqsen": "\\rdfInterface\\BlankNode",
            "name": "BlankNode",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-BlankNode.html"
        },                {
            "fqsen": "\\rdfInterface\\BlankNode\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-BlankNode.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\DataFactory",
            "name": "DataFactory",
            "summary": "",
            "url": "classes/rdfInterface-DataFactory.html"
        },                {
            "fqsen": "\\rdfInterface\\DataFactory\u003A\u003AnamedNode\u0028\u0029",
            "name": "namedNode",
            "summary": "",
            "url": "classes/rdfInterface-DataFactory.html#method_namedNode"
        },                {
            "fqsen": "\\rdfInterface\\DataFactory\u003A\u003AblankNode\u0028\u0029",
            "name": "blankNode",
            "summary": "",
            "url": "classes/rdfInterface-DataFactory.html#method_blankNode"
        },                {
            "fqsen": "\\rdfInterface\\DataFactory\u003A\u003Aliteral\u0028\u0029",
            "name": "literal",
            "summary": "",
            "url": "classes/rdfInterface-DataFactory.html#method_literal"
        },                {
            "fqsen": "\\rdfInterface\\DataFactory\u003A\u003Avariable\u0028\u0029",
            "name": "variable",
            "summary": "",
            "url": "classes/rdfInterface-DataFactory.html#method_variable"
        },                {
            "fqsen": "\\rdfInterface\\DataFactory\u003A\u003AdefaultGraph\u0028\u0029",
            "name": "defaultGraph",
            "summary": "",
            "url": "classes/rdfInterface-DataFactory.html#method_defaultGraph"
        },                {
            "fqsen": "\\rdfInterface\\DataFactory\u003A\u003Aquad\u0028\u0029",
            "name": "quad",
            "summary": "",
            "url": "classes/rdfInterface-DataFactory.html#method_quad"
        },                {
            "fqsen": "\\rdfInterface\\DataFactory\u003A\u003AquadTemplate\u0028\u0029",
            "name": "quadTemplate",
            "summary": "",
            "url": "classes/rdfInterface-DataFactory.html#method_quadTemplate"
        },                {
            "fqsen": "\\rdfInterface\\Dataset",
            "name": "Dataset",
            "summary": "Main,\u0020edge\u0028quad\u0029\u0020and\u0020Dataset\u002Doriented\u0020Dataset\u0020API",
            "url": "classes/rdfInterface-Dataset.html"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-Dataset.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/rdfInterface-Dataset.html#method___toString"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/rdfInterface-Dataset.html#method_equals"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003Acopy\u0028\u0029",
            "name": "copy",
            "summary": "",
            "url": "classes/rdfInterface-Dataset.html#method_copy"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AcopyExcept\u0028\u0029",
            "name": "copyExcept",
            "summary": "",
            "url": "classes/rdfInterface-Dataset.html#method_copyExcept"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003Aunion\u0028\u0029",
            "name": "union",
            "summary": "",
            "url": "classes/rdfInterface-Dataset.html#method_union"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003Axor\u0028\u0029",
            "name": "xor",
            "summary": "",
            "url": "classes/rdfInterface-Dataset.html#method_xor"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Adds\u0020set\u0020of\u0020quads.",
            "url": "classes/rdfInterface-Dataset.html#method_add"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/rdfInterface-Dataset.html#method_delete"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AdeleteExcept\u0028\u0029",
            "name": "deleteExcept",
            "summary": "",
            "url": "classes/rdfInterface-Dataset.html#method_deleteExcept"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AforEach\u0028\u0029",
            "name": "forEach",
            "summary": "Iterates\u0020trough\u0020all\u0020quads\u0020replacing\u0020them\u0020with\u0020a\u0020callback\u0020result.",
            "url": "classes/rdfInterface-Dataset.html#method_forEach"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/rdfInterface-Dataset.html#method_offsetExists"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/rdfInterface-Dataset.html#method_offsetGet"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/rdfInterface-Dataset.html#method_offsetSet"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/rdfInterface-Dataset.html#method_offsetUnset"
        },                {
            "fqsen": "\\rdfInterface\\DatasetCompare",
            "name": "DatasetCompare",
            "summary": "Main,\u0020edge\u0028quad\u0029\u0020and\u0020Dataset\u002Doriented\u0020Dataset\u0020API",
            "url": "classes/rdfInterface-DatasetCompare.html"
        },                {
            "fqsen": "\\rdfInterface\\DatasetCompare\u003A\u003Aevery\u0028\u0029",
            "name": "every",
            "summary": "",
            "url": "classes/rdfInterface-DatasetCompare.html#method_every"
        },                {
            "fqsen": "\\rdfInterface\\DatasetCompare\u003A\u003Anone\u0028\u0029",
            "name": "none",
            "summary": "",
            "url": "classes/rdfInterface-DatasetCompare.html#method_none"
        },                {
            "fqsen": "\\rdfInterface\\DatasetCompare\u003A\u003Aany\u0028\u0029",
            "name": "any",
            "summary": "",
            "url": "classes/rdfInterface-DatasetCompare.html#method_any"
        },                {
            "fqsen": "\\rdfInterface\\DatasetMapReduce",
            "name": "DatasetMapReduce",
            "summary": "Immutable\u0020edge\u0020processing\u0020methods",
            "url": "classes/rdfInterface-DatasetMapReduce.html"
        },                {
            "fqsen": "\\rdfInterface\\DatasetMapReduce\u003A\u003Amap\u0028\u0029",
            "name": "map",
            "summary": "",
            "url": "classes/rdfInterface-DatasetMapReduce.html#method_map"
        },                {
            "fqsen": "\\rdfInterface\\DatasetMapReduce\u003A\u003Areduce\u0028\u0029",
            "name": "reduce",
            "summary": "",
            "url": "classes/rdfInterface-DatasetMapReduce.html#method_reduce"
        },                {
            "fqsen": "\\rdfInterface\\DefaultGraph",
            "name": "DefaultGraph",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-DefaultGraph.html"
        },                {
            "fqsen": "\\rdfInterface\\DefaultGraph\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-DefaultGraph.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Literal",
            "name": "Literal",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-Literal.html"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Creates\u0020a\u0020new\u0020literal.",
            "url": "classes/rdfInterface-Literal.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "Returns\u0020literal\u0027s\u0020value.",
            "url": "classes/rdfInterface-Literal.html#method_getValue"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003AgetLang\u0028\u0029",
            "name": "getLang",
            "summary": "Returns\u0020literal\u0027s\u0020language\u0020tag.",
            "url": "classes/rdfInterface-Literal.html#method_getLang"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003AgetDatatype\u0028\u0029",
            "name": "getDatatype",
            "summary": "Returns\u0020literal\u0027s\u0020datatype.",
            "url": "classes/rdfInterface-Literal.html#method_getDatatype"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003AwithValue\u0028\u0029",
            "name": "withValue",
            "summary": "Returns\u0020a\u0020new\u0020literal\u0020being\u0020a\u0020copy\u0020of\u0020this\u0020one\u0020with\u0020a\u0020given\u0020value.",
            "url": "classes/rdfInterface-Literal.html#method_withValue"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003AwithLang\u0028\u0029",
            "name": "withLang",
            "summary": "Returns\u0020a\u0020new\u0020literal\u0020being\u0020a\u0020copy\u0020of\u0020this\u0020one\u0020with\u0020a\u0020lang\u0020tag\u0020set\u0020to\na\u0020given\u0020value.",
            "url": "classes/rdfInterface-Literal.html#method_withLang"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003AwithDatatype\u0028\u0029",
            "name": "withDatatype",
            "summary": "Returns\u0020a\u0020new\u0020literal\u0020being\u0020a\u0020copy\u0020with\u0020this\u0020one\u0020with\u0020datatype\u0020set\u0020to\na\u0020given\u0020value.",
            "url": "classes/rdfInterface-Literal.html#method_withDatatype"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003ACAST_LEXICAL_FORM",
            "name": "CAST_LEXICAL_FORM",
            "summary": "",
            "url": "classes/rdfInterface-Literal.html#constant_CAST_LEXICAL_FORM"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003ACAST_DATATYPE",
            "name": "CAST_DATATYPE",
            "summary": "",
            "url": "classes/rdfInterface-Literal.html#constant_CAST_DATATYPE"
        },                {
            "fqsen": "\\rdfInterface\\NamedNode",
            "name": "NamedNode",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-NamedNode.html"
        },                {
            "fqsen": "\\rdfInterface\\NamedNode\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-NamedNode.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Parser",
            "name": "Parser",
            "summary": "",
            "url": "classes/rdfInterface-Parser.html"
        },                {
            "fqsen": "\\rdfInterface\\Parser\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-Parser.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Parser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/rdfInterface-Parser.html#method_parse"
        },                {
            "fqsen": "\\rdfInterface\\Parser\u003A\u003AparseStream\u0028\u0029",
            "name": "parseStream",
            "summary": "",
            "url": "classes/rdfInterface-Parser.html#method_parseStream"
        },                {
            "fqsen": "\\rdfInterface\\Quad",
            "name": "Quad",
            "summary": "Extends\u0020Term\u0020because\u0020of\u0020RDF\u002A",
            "url": "classes/rdfInterface-Quad.html"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AgetSubject\u0028\u0029",
            "name": "getSubject",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_getSubject"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AgetPredicate\u0028\u0029",
            "name": "getPredicate",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_getPredicate"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AgetObject\u0028\u0029",
            "name": "getObject",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_getObject"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AgetGraphIri\u0028\u0029",
            "name": "getGraphIri",
            "summary": "Null\u0020is\u0020not\u0020allowed\u0020to\u0020deal\u0020with\u0020the\u0020ambiguity\u0020between\u0020DefaultGraph\u0020and\nnull\u0020which\u0020mean\u0020the\u0020same\u0020\u0028although\u0020it\u0020should\u0020be\u0020noted\u0020that\u0020all\u0020quads\u0020in\nNamedNode\/BlankNode\u0020graphs\u0020also\u0020belong\u0020to\u0020the\u0020DefaultGraph\u0029.",
            "url": "classes/rdfInterface-Quad.html#method_getGraphIri"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AwithSubject\u0028\u0029",
            "name": "withSubject",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_withSubject"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AwithPredicate\u0028\u0029",
            "name": "withPredicate",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_withPredicate"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AwithObject\u0028\u0029",
            "name": "withObject",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_withObject"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AwithGraphIri\u0028\u0029",
            "name": "withGraphIri",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_withGraphIri"
        },                {
            "fqsen": "\\rdfInterface\\QuadIterator",
            "name": "QuadIterator",
            "summary": "",
            "url": "classes/rdfInterface-QuadIterator.html"
        },                {
            "fqsen": "\\rdfInterface\\QuadIterator\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "",
            "url": "classes/rdfInterface-QuadIterator.html#method_current"
        },                {
            "fqsen": "\\rdfInterface\\QuadTemplate",
            "name": "QuadTemplate",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-QuadTemplate.html"
        },                {
            "fqsen": "\\rdfInterface\\QuadTemplate\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "At\u0020least\u0020one\u0020parameter\u0020has\u0020to\u0020be\u0020not\u0020null.",
            "url": "classes/rdfInterface-QuadTemplate.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\QuadTemplate\u003A\u003AgetSubject\u0028\u0029",
            "name": "getSubject",
            "summary": "",
            "url": "classes/rdfInterface-QuadTemplate.html#method_getSubject"
        },                {
            "fqsen": "\\rdfInterface\\QuadTemplate\u003A\u003AgetPredicate\u0028\u0029",
            "name": "getPredicate",
            "summary": "",
            "url": "classes/rdfInterface-QuadTemplate.html#method_getPredicate"
        },                {
            "fqsen": "\\rdfInterface\\QuadTemplate\u003A\u003AgetObject\u0028\u0029",
            "name": "getObject",
            "summary": "",
            "url": "classes/rdfInterface-QuadTemplate.html#method_getObject"
        },                {
            "fqsen": "\\rdfInterface\\QuadTemplate\u003A\u003AgetGraphIri\u0028\u0029",
            "name": "getGraphIri",
            "summary": "DefaultGraph\u0020is\u0020skipped\u0020to\u0020avoid\u0020ambiguity\u0020between\u0020null\u0020and\u0020DefaultGraph\n\u0028as\u0020all\u0020quads\u0020belong\u0020to\u0020the\u0020DefaultGraph\u0020it\u0020effectively\u0020means\u0020no\u0020filter\u0020at\nall,\u0020just\u0020like\u0020null\u0029.",
            "url": "classes/rdfInterface-QuadTemplate.html#method_getGraphIri"
        },                {
            "fqsen": "\\rdfInterface\\QuadTemplate\u003A\u003AwithSubject\u0028\u0029",
            "name": "withSubject",
            "summary": "",
            "url": "classes/rdfInterface-QuadTemplate.html#method_withSubject"
        },                {
            "fqsen": "\\rdfInterface\\QuadTemplate\u003A\u003AwithPredicate\u0028\u0029",
            "name": "withPredicate",
            "summary": "",
            "url": "classes/rdfInterface-QuadTemplate.html#method_withPredicate"
        },                {
            "fqsen": "\\rdfInterface\\QuadTemplate\u003A\u003AwithObject\u0028\u0029",
            "name": "withObject",
            "summary": "",
            "url": "classes/rdfInterface-QuadTemplate.html#method_withObject"
        },                {
            "fqsen": "\\rdfInterface\\QuadTemplate\u003A\u003AwithGraphIri\u0028\u0029",
            "name": "withGraphIri",
            "summary": "",
            "url": "classes/rdfInterface-QuadTemplate.html#method_withGraphIri"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace",
            "name": "RdfNamespace",
            "summary": "",
            "url": "classes/rdfInterface-RdfNamespace.html"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Registers\u0020a\u0020given\u0020URL\u0020prefix.",
            "url": "classes/rdfInterface-RdfNamespace.html#method_add"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Drops\u0020a\u0020given\u0020short\u0020name\u0020and\u0020IRI\u0020prefix\u0020associated\u0020with\u0020it.",
            "url": "classes/rdfInterface-RdfNamespace.html#method_remove"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Returns\u0020a\u0020IRI\u0020prefix\u0020for\u0020a\u0020given\u0020short\u0020name.",
            "url": "classes/rdfInterface-RdfNamespace.html#method_get"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace\u003A\u003AgetAll\u0028\u0029",
            "name": "getAll",
            "summary": "Returns\u0020associative\u0020array\u0020of\u0020all\u0020registered\u0020namespaces\u0020with\u0020array\u0020keys\nbeing\u0020namespace\u0020short\u0020names\u0020and\u0020array\u0020values\u0020containing\u0020URL\u0020prefixes.",
            "url": "classes/rdfInterface-RdfNamespace.html#method_getAll"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace\u003A\u003Aexpand\u0028\u0029",
            "name": "expand",
            "summary": "Expands\u0020a\u0020shortened\u0020IRI\u0020to\u0020a\u0020NamedNode.",
            "url": "classes/rdfInterface-RdfNamespace.html#method_expand"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace\u003A\u003Ashorten\u0028\u0029",
            "name": "shorten",
            "summary": "Shortens\u0020provided\u0020NamedNode\u0020IRI.",
            "url": "classes/rdfInterface-RdfNamespace.html#method_shorten"
        },                {
            "fqsen": "\\rdfInterface\\Serializer",
            "name": "Serializer",
            "summary": "",
            "url": "classes/rdfInterface-Serializer.html"
        },                {
            "fqsen": "\\rdfInterface\\Serializer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-Serializer.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Serializer\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "",
            "url": "classes/rdfInterface-Serializer.html#method_serialize"
        },                {
            "fqsen": "\\rdfInterface\\Serializer\u003A\u003AserializeStream\u0028\u0029",
            "name": "serializeStream",
            "summary": "",
            "url": "classes/rdfInterface-Serializer.html#method_serializeStream"
        },                {
            "fqsen": "\\rdfInterface\\Term",
            "name": "Term",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-Term.html"
        },                {
            "fqsen": "\\rdfInterface\\Term\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/rdfInterface-Term.html#method___toString"
        },                {
            "fqsen": "\\rdfInterface\\Term\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "",
            "url": "classes/rdfInterface-Term.html#method_getValue"
        },                {
            "fqsen": "\\rdfInterface\\Term\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/rdfInterface-Term.html#method_equals"
        },                {
            "fqsen": "\\rdfInterface\\Variable",
            "name": "Variable",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-Variable.html"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\simpleRdf",
            "name": "simpleRdf",
            "summary": "",
            "url": "namespaces/simplerdf.html"
        },                {
            "fqsen": "\\rdfHelpers",
            "name": "rdfHelpers",
            "summary": "",
            "url": "namespaces/rdfhelpers.html"
        },                {
            "fqsen": "\\rdfInterface",
            "name": "rdfInterface",
            "summary": "",
            "url": "namespaces/rdfinterface.html"
        }            ]
);
